spring:
  profiles:
    active: usage_message
    rabbitmq:
      user: guest
      password: guest
      host: rabbitmq
      port: 5672

logging:
  level:
    org: ERROR

tutorial:
  client:
    duration: 10000